name: Go

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: 
          - '1.19'
          - '1.20'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build main executable
      run: go build -o main .

    - name: Run Go tests
      run: go test -v ./...

    - name: Install jq
      run: sudo apt-get install jq

    - name: Run bash tests
      run: |
        chmod +x test.sh
        ./test.sh
